ProyectoTallerEquipo2/Taller.App/Taller.App.Front/Pages/Revisiones/EditarRevisiones.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Taller.App.Persistencia;
using Taller.App.Dominio.Entidades;

namespace Talle.App.Front.Pages
{
    public class EditarRevisionesModel : PageModel
    {
        private static RepositorioRevision repoRevision = new RepositorioRevision(
           new ContextDb()
        );

        private static RepositorioMecanico repoMecanico = new RepositorioMecanico(
            new ContextDb()
        );

        private static RepositorioRepuesto repoRepuesto = new RepositorioRepuesto(
        new ContextDb()
        );
        private static RepositorioVehiculo repoVehiculo = new RepositorioVehiculo(
        new ContextDb()
        );
        public List<Repuesto> listaRepuestos = new List<Repuesto>();
        public Revision revisionActual { get; set;}
        public Mecanico mecanicoActual { get; set;}
        public Repuesto repuestoActual { get; set;}
        public Vehiculo vehiculoActual { get; set;}
        public IActionResult OnGet(string revisionId)
        {
            try {
                this.ObtenerRepuestos();
                this.revisionActual = repoRevision.BuscarRevision(revisionId);
                this.mecanicoActual = repoMecanico.BuscarMecanico(revisionActual.MecanicoId);
                this.vehiculoActual = repoVehiculo.BuscarVehiculo(revisionActual.VehiculoId);
                return Page();
            } catch {
                return RedirectToPage("./Error");
            }
        }

        public IActionResult OnPostEditar(Revision revisionActual, string revisionId)
        {
            try
            {
                revisionActual.MecanicoId = mecanicoActual.MecanicoId;
                revisionActual.VehiculoId = vehiculoActual.VehiculoId;
                repoRevision.EditarRevision(revisionActual, revisionId);
                repoRevision.ObtenerRevisiones();
                return RedirectToPage("/Revisiones/ListadoRevisiones");
            }
            catch
            {
                Console.WriteLine("error");
                throw;
            }
        }

        private void ObtenerRepuestos()
        {
            foreach (Repuesto repuesto in repoRepuesto.ObtenerRepuestos())
            {
                this.listaRepuestos.Add(new Repuesto
                {
                    RepuestoId = repuesto.RepuestoId,
                    Tipo = repuesto.Tipo,
                    Nombre = repuesto.Nombre,
                    Cantidad = repuesto.Cantidad
                });
            }
        }
    }
}

ProyectoTallerEquipo2/Taller.App/Taller.App.Front/Pages/Revisiones/ListadoRevisiones.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Taller.App.Persistencia;
using Taller.App.Dominio.Entidades;

namespace Taller.App.Front.Pages
{
    public class ListadoRevisionesModel : PageModel
    {
        private static RepositorioRevision repoRevision = new RepositorioRevision(
           new Persistencia.ContextDb()
       );

        private static RepositorioMecanico repoMecanico = new RepositorioMecanico(
            new Persistencia.ContextDb()
        );

        private static RepositorioRepuesto repoRepuesto = new RepositorioRepuesto(
        new Persistencia.ContextDb()
        );
        private static RepositorioVehiculo repoVehiculo = new RepositorioVehiculo(
        new Persistencia.ContextDb()
        );
        public List<Revision> listaRevisiones = new List<Revision>();
        public List<Mecanico> listaMecanicos = new List<Mecanico>();
        public List<Repuesto> listaRepuestos = new List<Repuesto>();
        public List<Vehiculo> listaVehiculos = new List<Vehiculo>();
        public Revision revisionActual;
        public Mecanico mecanicoActual;
        public Repuesto repuestoActual;
        public Vehiculo vehiculoActual;

        public void OnGet()
        {
            this.ObtenerRevisiones();
            this.ObtenerMecanicos();
            this.ObtenerRepuestos();
            this.ObtenerVehiculos();
        }

        public void OnPostAgregarRevision(Revision revision)
        {
            try
            {
                repoRevision.AgregarRevision(revision);
                this.ObtenerRevisiones();
                this.ObtenerMecanicos();
                this.ObtenerRepuestos();
                this.ObtenerVehiculos();
            }
            catch
            {
                throw;
            }
        }

        public void OnPostEliminarRevision(string id)
        {
            Console.WriteLine("llego" + id);
            try
            {
                repoRevision.EliminarRevision(id);
                this.ObtenerRevisiones();
            }
            catch
            {
                throw;
            }
        }
        private void ObtenerRevisiones()
        {
            foreach (Revision revision in repoRevision.ObtenerRevisiones())
            {
                this.listaRevisiones.Add(new Revision
                {
                    RevisionId = revision.RevisionId,
                    FechaEntrada = revision.FechaEntrada,
                    FechaSalida = revision.FechaSalida,
                    Observaciones = revision.Observaciones,
                    VehiculoId = revision.VehiculoId,
                    MecanicoId = revision.MecanicoId,
                    RepuestoId = revision.RepuestoId
                });
            }
        }

        private void ObtenerMecanicos()
        {
            foreach (Mecanico mecanico in repoMecanico.ObtenerMecanicos())
            {
                this.listaMecanicos.Add(new Mecanico
                {
                    MecanicoId = mecanico.MecanicoId,
                    Nombre = mecanico.Nombre,
                    Apellido = mecanico.Apellido
                });
            }

        }
        private void ObtenerRepuestos()
        {
            foreach (Repuesto repuesto in repoRepuesto.ObtenerRepuestos())
            {
                this.listaRepuestos.Add(new Repuesto
                {
                    RepuestoId = repuesto.RepuestoId,
                    Tipo = repuesto.Tipo,
                    Nombre = repuesto.Nombre,
                    Cantidad = repuesto.Cantidad
                });
            }
        }
        private void ObtenerVehiculos()
        {
            foreach (Vehiculo vehiculo in repoVehiculo.ObtenerVehiculos())
            {
                this.listaVehiculos.Add(new Vehiculo
                {
                    VehiculoId = vehiculo.VehiculoId,
                    Placa = vehiculo.Placa,
                    Modelo = vehiculo.Modelo,
                    Marca = vehiculo.Marca
                });
            }
        }

    }
}

ProyectoTallerEquipo2/Taller.App/Taller.App.Front/Pages/Revisiones/EditarRevisiones.cshtml
@page
@model Talle.App.Front.Pages.EditarRevisionesModel
@{
    <form method="post">
        <div class="row">
            <div class="mb-3 col-4">
                <label for="entradaId" class="form-label col-form-label">Id *</label>
                <input type="text" class="form-control" id="entradaId" name="RevisionId" required asp-for="@Model.revisionActual.RevisionId" disabled="true">
            </div>
            <div class="row">
                <div class="mb-3 col-6">
                    <label for="entradaFechaEntrada" class="form-label col-form-label">Fecha Entrada
                        *</label>
                    <input type="date" class="form-control" id="entradaFechaEntrada"
                        asp-for="@Model.revisionActual.FechaEntrada" name="FechaEntrada" required disabled="true">
                </div>
                <div class="mb-3 col-6">
                    <label for="entradaFechaSalida" class="form-label col-form-label">Fecha Salida *</label>
                    <input type="date" class="form-control" id="entradaFechaSalida" rows="3"
                        asp-for="@Model.revisionActual.FechaSalida" name="FechaSalida" required>
                </div>
            </div>
            <div class="row">
                <div class="mb-3 col-6">
                    <label for="entradaObservaciones" class="form-label col-form-label">Observaciones
                        *</label>
                    <input type="text" class="form-control" id="entradaObservaciones" rows="3"
                        asp-for="@Model.revisionActual.Observaciones" name="Observaciones" required>
                </div>
                <div class="mb-3 col-6">
                    <label for="entradaVehiculoId" class="form-label col-form-label">Vehiculo *</label>
                    <input class="form-control" id="entradaVehiculoId" name="Vehiculo"
                        asp-for="@Model.vehiculoActual.Placa" disabled="true">

                </div>
            </div>
            <div class="row">
                <div class="mb-3 col-6">
                    <label for="entradaMecanicoId" class="form-label col-form-label">Mecanico *</label>
                    <input class="form-control" id="entradaMecanicoId" name="Mecanico"
                        asp-for="@Model.mecanicoActual.Nombre" name="Mecanico" required disabled="true">
                </div>
                <div class="mb-3 col-6">
                    <label for="entradaRepuestoId" class="form-label col-form-label">Repuesto *</label>
                    <select class="form-select" id="entradaRepuestoId" aria-label="Selecciona una Opción"
                        asp-for="@Model.repuestoActual.RepuestoId" name="RepuestoId" required>
                        @foreach (var m in @Model.listaRepuestos)
                        {
                            <option value="@m.RepuestoId">@m.RepuestoId - @m.Nombre</option>
                        }
                    </select>
                </div>
            </div>
        </div>
        <a asp-page="/Revisiones/ListadoRevisiones" class="btn btn-secondary">Cancelar</a>
        <button type="submit" class="btn btn-primary" asp-page-handler="Editar" asp-route-revisionId="@Model.revisionActual.RevisionId">Editar</button>
    </form>
}

ProyectoTallerEquipo2/Taller.App/Taller.App.Front/Pages/Revisiones/ListadoRevisiones.cshtml
@page
@model Taller.App.Front.Pages.ListadoRevisionesModel
@{
}

<div class="class-contain-title">
    <form method="post">
    <h4>Adicionar una Revisión <i class="bi bi-plus-square-fill class-icon-add" title="Agregar Revisión"
            data-bs-toggle="modal" data-bs-target="#idModalRevision" @* asp-page-handler="ObtenerMecanicos" *@></i></h4>
    </form>
    <form class="form-inline class-search-bar">
        <input type="search" class="form-control mr-sm-2" id="inputBuscar" placeholder="Buscar">
        <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">Buscar</button>
    </form>
</div>
<hr class="border border-primary border-3 opacity-75">
<h3>Datos Revisiones</h3>
<div>
    <form class="">
        <table class="table">
            <thead>
                <tr class="table-primary">
                    <th scope="col">Id</th>
                    <th scope="col">Fecha Entrada</th>
                    <th scope="col">Fecha Salida</th>
                    <th scope="col">Observaciones</th>
                    <th scope="col">Id Vehiculo</th>
                    <th scope="col">Id Mecanico</th>
                    <th scope="col">Id Repuesto</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var re in @Model.listaRevisiones)
                {
                    <tr>
                        <td>@re.RevisionId</td>
                        <td>@re.FechaEntrada</td>
                        <td>@re.FechaSalida</td>
                        <td>@re.Observaciones</td>
                        <td>@re.VehiculoId</td>
                        <td>@re.MecanicoId</td>
                        <td>@re.RepuestoId</td>
                        <td style="display: flex;">
                            <a asp-page="/Revisiones/EditarRevisiones" asp-route-revisionId="@re.RevisionId">
                                <i class="bi bi-pencil-fill class-icon-edit" title="Editar Revision"></i>
                            </a>
                            <form method="post">
                                <button class="bi bi-trash3-fill class-icon-del" asp-route-id="@re.RevisionId"
                                asp-page-handler="EliminarRevision" type="submit"></button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </form>
</div>
<div class="modal fade" id="idModalRevision" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Adicionar una Revisión</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post">
                    <div class="row">
                        <div class="mb-3 col-4">
                            <label for="entradaId" class="form-label col-form-label">Id *</label>
                            <input type="text" class="form-control" id="entradaId" name="RevisionId" required>
                        </div>
                        <div class="row">
                            <div class="mb-3 col-6">
                                <label for="entradaFechaEntrada" class="form-label col-form-label">Fecha Entrada
                                    *</label>
                                <input type="date" class="form-control" id="entradaFechaEntrada"
                                    asp-for="@Model.revisionActual.FechaEntrada" name="FechaEntrada" required>
                            </div>
                            <div class="mb-3 col-6">
                                <label for="entradaFechaSalida" class="form-label col-form-label">Fecha Salida *</label>
                                <input type="date" class="form-control" id="entradaFechaSalida" rows="3"
                                    asp-for="@Model.revisionActual.FechaSalida" name="FechaSalida" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-3 col-6">
                                <label for="entradaObservaciones" class="form-label col-form-label">Observaciones
                                    *</label>
                                <input type="text" class="form-control" id="entradaObservaciones" rows="3"
                                    asp-for="@Model.revisionActual.Observaciones" name="Observaciones" required>
                            </div>
                            <div class="mb-3 col-6">
                                <label for="entradaVehiculoId" class="form-label col-form-label">Vehiculo *</label>
                                <select class="form-select" id="entradaVehiculoId" aria-label="Selecciona una Opción"
                                    asp-for="@Model.vehiculoActual.VehiculoId" name="VehiculoId" required>
                                    @foreach (var v in @Model.listaVehiculos)
                                    {
                                        <option value="@v.VehiculoId">@v.VehiculoId - @v.Placa @v.Modelo</option>
                                    }
                                    </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-3 col-6">
                                <label for="entradaVehiculoId" class="form-label col-form-label">Mecanico *</label>
                                <select class="form-select" id="entradaNivelEstudios" aria-label="Selecciona una Opción"
                                    asp-for="@Model.mecanicoActual.MecanicoId" name="MecanicoId" required>
                                    @foreach (var m in @Model.listaMecanicos)
                                    {
                                        <option value="@m.MecanicoId">@m.MecanicoId - @m.Nombre @m.Apellido</option>
                                    }
                                    </select>
                            </div>
                            <div class="mb-3 col-6">
                                <label for="entradaRepuestoId" class="form-label col-form-label">Repuesto *</label>
                                <select class="form-select" id="entradaRepuestoId" aria-label="Selecciona una Opción"
                                    asp-for="@Model.repuestoActual.RepuestoId" name="RepuestoId" required>
                                    @foreach (var m in @Model.listaRepuestos)
                                    {
                                        <option value="@m.RepuestoId">@m.RepuestoId - @m.Nombre</option>
                                    }
                                    </select>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                                <button type="submit" class="btn btn-primary"
                                    asp-page-handler="AgregarRevision">Agregar</button>
                            </div>
                </form>
            </div>
        </div>
    </div>
</div>