ProyectoTallerEquipo2/Taller.App/Taller.App.Front/Pages/Mecanicos/EditarMecanico.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Taller.App.Persistencia;
using Taller.App.Dominio.Entidades;

namespace Talle.App.Front.Pages
{
    public class EditarMecanicoModel : PageModel
    {
        private static RepositorioMecanico repoMecanico = new RepositorioMecanico(
            new ContextDb()
        );

        public List<String> ciudades = new List<String>(){
            "Bogotá", "Medellín", "Manizales", "Barranquilla"
        };

        public List<String> especialidades = new List<String>(){
            "Eléctrico", "Mecánico", "Pintor", "Soldador"
        };

        public List<String> nivelEstudio = new List<String>(){
            "Bachiller", "Técnico", "Tecnólogo"
        };

        public Mecanico mecanicoActual;
        public IActionResult OnGet(string mecanicoId)
        {
            try {
                mecanicoActual = repoMecanico.BuscarMecanico(mecanicoId);
                return Page();
            } catch {
                return RedirectToPage("./Error");
            }
        }

        public IActionResult OnPostEditar(Mecanico mecanicoActual, string MecanicoId)
        {
            try
            {
                repoMecanico.EditarMecanico(mecanicoActual, MecanicoId);
                repoMecanico.ObtenerMecanicos();
                return RedirectToPage("/Mecanicos/GestionMecanico");
            }
            catch
            {
                Console.WriteLine("error");
                throw;
            }
        }
    }
}

ProyectoTallerEquipo2/Taller.App/Taller.App.Front/Pages/Mecanicos/GestionMecanico.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Taller.App.Persistencia;
using Taller.App.Dominio.Entidades;

namespace Taller.App.Front.Pages
{
    public class GestionMecanicoModel : PageModel
    {
        private static RepositorioMecanico repoMecanico = new RepositorioMecanico(
            new Persistencia.ContextDb()
        );

        public List<String> ciudades = new List<String>(){
            "Bogotá", "Medellín", "Manizales", "Barranquilla"
        };

        public List<String> especialidades = new List<String>(){
            "Eléctrico", "Mecánico", "Pintor", "Soldador"
        };

        public List<String> nivelEstudio = new List<String>(){
            "Bachiller", "Técnico", "Tecnólogo"
        };

        public List<Mecanico> listaMecanicos = new List<Mecanico>();

        public Mecanico mecanicoActual;

        public void OnGet()
        {
            this.ObtenerMecanicos();
        }

        public void OnPostAgregarMecanico(Mecanico mecanico)
        {
            try
            {
                repoMecanico.AgregarMecanico(mecanico);
                this.ObtenerMecanicos();
            }
            catch
            {
                throw;
            }
        }

        public void OnPostEliminarMecanico(string id)
        {
            try
            {
                repoMecanico.EliminarMecanico(id);
                this.ObtenerMecanicos();
            }
            catch
            {
                throw;
            }
        }
        private void ObtenerMecanicos()
        {
            foreach (Mecanico mecanico in repoMecanico.ObtenerMecanicos())
            {
                this.listaMecanicos.Add(new Mecanico
                {
                    MecanicoId = mecanico.MecanicoId,
                    Nombre = mecanico.Nombre,
                    Apellido = mecanico.Apellido,
                    Telefono = mecanico.Telefono,
                    NivelEstudio = mecanico.NivelEstudio,
                    Rol = mecanico.Rol
                });
            }
        }
    }
}

ProyectoTallerEquipo2/Taller.App/Taller.App.Front/Pages/Mecanicos/EditarMecanico.cshtml
@page
@model Talle.App.Front.Pages.EditarMecanicoModel
@{
    <form method="post">
        <div class="row">
            <div class="mb-3 col-4">
                <label for="entradaId" class="form-label col-form-label">Id *</label>
                <input type="text" class="form-control" id="entradaId" name="MecanicoId" asp-for="@Model.mecanicoActual.MecanicoId" required disabled="true">
            </div>
            <div class="row">
                <div class="mb-3 col-6">
                    <label for="entradaNombres" class="form-label col-form-label">Nombres *</label>
                    <input type="text" class="form-control" id="entradaNombres" asp-for="@Model.mecanicoActual.Nombre"
                        name="Nombre" required>
                </div>
                <div class="mb-3 col-6">
                    <label for="entradaApellidos" class="form-label col-form-label">Apellidos *</label>
                    <input type="text" class="form-control" id="entradaApellidos" rows="3"
                        asp-for="@Model.mecanicoActual.Apellido" name="Apellido" required>
                </div>
            </div>
            <div class="row">
                <div class="mb-3 col-6">
                    <label for="entradaCelular" class="form-label col-form-label">Número de celular
                        *</label>
                    <input type="text" class="form-control" id="entradaCelular" rows="3"
                        asp-for="@Model.mecanicoActual.Telefono" name="Telefono" required>
                </div>
                <div class="mb-3 col-6">
                    <label for="entradaFechaNacimiento" class="form-label col-form-label">Fecha de
                        nacimiento *</label>
                    <input type="date" class="form-control" id="entradaFechaNacimiento" rows="3"
                        asp-for="@Model.mecanicoActual.FechaNacimiento" name="FechaNacimiento" required>
                </div>
            </div>
            <div class="row">
                <div class="mb-3 col-6">
                    <label for="entradaDireccion" class="form-label col-form-label">Dirección de residencia
                        *</label>
                    <input type="text" class="form-control" id="entradaDireccion" rows="3"
                        asp-for="@Model.mecanicoActual.Direccion" name="Direccion" required>
                </div>
                <div class="mb-3 col-6">
                    <label for="entradaNivelEstudios" class="form-label col-form-label">Nivel de estudios
                        *</label>
                    <select class="form-select" id="entradaNivelEstudios" aria-label="Selecciona una Opción"
                        asp-for="@Model.mecanicoActual.NivelEstudio" name="NivelEstudio" required>
                        <option value="Bachiller">Bachiller</option>
                        <option value="Técnico">Técnico</option>
                        <option value="Tecnólogo">Tecnólogo</option>
                        <option value="Profesional">Profesional</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="mb-3 col-6">
                    <label for="entradaContrasenia" class="form-label">Contraseña *</label>
                    <input type="password" class="form-control" id="entradaContrasenia" rows="3"
                        asp-for="@Model.mecanicoActual.Contrasenia" name="Contrasenia" required>
                </div>
                <div class="mb-3 col-6">
                    <label for="entradaRol" class="form-label">Rol *</label>
                    <select class="form-select" id="entradaRol" asp-for="@Model.mecanicoActual.Rol" name="Rol" required>
                        <option value="Mecánico">Mecánico</option>
                    </select>
                </div>
            </div>
        </div>
        <a asp-page="/Mecanicos/GestionMecanico" class="btn btn-secondary">Cancelar</a>
        <button type="submit" class="btn btn-primary" asp-page-handler="Editar" asp-route-mecanicoId="@Model.mecanicoActual.MecanicoId">Editar</button>
    </form>
}

ProyectoTallerEquipo2/Taller.App/Taller.App.Front/Pages/Mecanicos/GestionMecanico.cshtml
@page
@model Taller.App.Front.Pages.GestionMecanicoModel
@{
}

<div class="class-contain-title">
    <h4>Adicionar un Mecánico <i class="bi bi-plus-square-fill class-icon-add" title="Agregar Mecánico"
            data-bs-toggle="modal" data-bs-target="#idModalMecanico"></i></h4>
    <form class="form-inline class-search-bar">
        <input type="search" class="form-control mr-sm-2" id="inputBuscar" placeholder="Buscar">
        <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">Buscar</button>
    </form>
</div>
<hr class="border border-primary border-3 opacity-75">
<h3>Datos Mecánicos</h3>
<div>
<form class="">
    <table class="table">
        <thead>
            <tr class="table-primary">
                <th scope="col">Id</th>
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">Teléfono</th>
                <th scope="col">Rol</th>
                <th scope="col">Nivel Estudio</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var m in @Model.listaMecanicos)
            {
                <tr>
                    <td>@m.MecanicoId</td>
                    <td>@m.Nombre</td>
                    <td>@m.Apellido</td>
                    <td>@m.Telefono</td>
                    <td>@m.Rol</td>
                    <td>@m.NivelEstudio</td>
                    <td style="display: flex;">
                        <a asp-page="/Mecanicos/EditarMecanico" asp-route-mecanicoId="@m.MecanicoId">
                            <i class="bi bi-pencil-fill class-icon-edit" title="Editar Mecanico"></i>
                        </a>
                        <form method="post">
                            <button class="bi bi-trash3-fill class-icon-del" asp-route-id="@m.MecanicoId"
                            asp-page-handler="EliminarMecanico" type="submit"></button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>
</div>
<div class="modal fade" id="idModalMecanico" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Agregar un Mecanico</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post">
                    <div class="row">
                        <div class="mb-3 col-4">
                            <label for="entradaId" class="form-label col-form-label">Id *</label>
                            <input type="text" class="form-control" id="entradaId" name="MecanicoId" required>
                        </div>
                        <div class="row">
                            <div class="mb-3 col-6">
                                <label for="entradaNombres" class="form-label col-form-label">Nombres *</label>
                                <input type="text" class="form-control" id="entradaNombres"
                                    asp-for="@Model.mecanicoActual.Nombre" name="Nombre" required>
                            </div>
                            <div class="mb-3 col-6">
                                <label for="entradaApellidos" class="form-label col-form-label">Apellidos *</label>
                                <input type="text" class="form-control" id="entradaApellidos" rows="3"
                                    asp-for="@Model.mecanicoActual.Apellido" name="Apellido" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-3 col-6">
                                <label for="entradaCelular" class="form-label col-form-label">Número de celular
                                    *</label>
                                <input type="text" class="form-control" id="entradaCelular" rows="3"
                                    asp-for="@Model.mecanicoActual.Telefono" name="Telefono" required>
                            </div>
                            <div class="mb-3 col-6">
                                <label for="entradaFechaNacimiento" class="form-label col-form-label">Fecha de
                                    nacimiento *</label>
                                <input type="date" class="form-control" id="entradaFechaNacimiento" rows="3"
                                    asp-for="@Model.mecanicoActual.FechaNacimiento" name="FechaNacimiento" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-3 col-6">
                                <label for="entradaDireccion" class="form-label col-form-label">Dirección de residencia
                                    *</label>
                                <input type="text" class="form-control" id="entradaDireccion" rows="3"
                                    asp-for="@Model.mecanicoActual.Direccion" name="Direccion" required>
                            </div>
                            <div class="mb-3 col-6">
                                <label for="entradaNivelEstudios" class="form-label col-form-label">Nivel de estudios
                                    *</label>
                                <select class="form-select" id="entradaNivelEstudios" aria-label="Selecciona una Opción"
                                    asp-for="@Model.mecanicoActual.NivelEstudio" name="NivelEstudio" required>
                                    <option value="Bachiller">Bachiller</option>
                                    <option value="Técnico">Técnico</option>
                                    <option value="Tecnólogo">Tecnólogo</option>
                                    <option value="Profesional">Profesional</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-3 col-6">
                                <label for="entradaContrasenia" class="form-label">Contraseña *</label>
                                <input type="password" class="form-control" id="entradaContrasenia" rows="3"
                                    asp-for="@Model.mecanicoActual.Contrasenia" name="Contrasenia" required>
                            </div>
                            <div class="mb-3 col-6">
                                <label for="entradaRol" class="form-label">Rol *</label>
                                <select class="form-select" id="entradaRol" asp-for="@Model.mecanicoActual.Rol"
                                    name="Rol" required>
                                    <option value="Mecánico">Mecánico</option>
                                </select>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                            <button type="submit" class="btn btn-primary"
                                asp-page-handler="AgregarMecanico">Agregar</button>
                        </div>
                </form>
            </div>
        </div>
    </div>
</div>