ProyectoTallerEquipo2/Taller.App/Taller.App.Front/Pages/Propietarios/EditarCliente.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Taller.App.Persistencia;
using Taller.App.Dominio.Entidades;

namespace Talle.App.Front.Pages
{
    public class EditarClienteModel : PageModel
    {
        private static RepositorioCliente repoCliente = new RepositorioCliente(
            new ContextDb()
        );

        public List<String> ciudades = new List<String>(){
            "Bogotá", "Medellín", "Manizales", "Barranquilla"
        };

        public List<String> especialidades = new List<String>(){
            "Eléctrico", "Mecánico", "Pintor", "Soldador"
        };

        public List<String> nivelEstudio = new List<String>(){
            "Bachiller", "Técnico", "Tecnólogo"
        };

        public Cliente clienteActual;
        public IActionResult OnGet(string clienteId)
        {
            try {
                clienteActual = repoCliente.BuscarCliente(clienteId);
                return Page();
            } catch {
                return RedirectToPage("./Error");
            }
        }

        public IActionResult OnPostEditar(Cliente clienteActual, string clienteId)
        {
            try
            {
                repoCliente.EditarCliente(clienteActual, clienteId);
                repoCliente.ObtenerClientes();
                return RedirectToPage("/Propietarios/RegistroPropietario");
            }
            catch
            {
                Console.WriteLine("error");
                throw;
            }
        }
    }
}

ProyectoTallerEquipo2/Taller.App/Taller.App.Front/Pages/Propietarios/RegistroPropietario.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Taller.App.Persistencia;
using Taller.App.Dominio.Entidades;

namespace Taller.App.Front.Pages
{
    public class RegistroPropietarioModel : PageModel
    {

        private static RepositorioCliente repoCliente = new RepositorioCliente(
            new Persistencia.ContextDb()
        );

        public List<String> ciudades = new List<String>(){
            "Bogotá", "Medellín", "Manizales", "Barranquilla"
        };

        public List<String> especialidades = new List<String>(){
            "Eléctrico", "Mecánico", "Pintor", "Soldador"
        };

        public List<String> nivelEstudio = new List<String>(){
            "Bachiller", "Técnico", "Tecnólogo"
        };

        public List<Cliente> listaClientes = new List<Cliente>();

        public Cliente clienteActual;

        public void OnGet()
        {
            this.ObtenerClientes();
        }

        public void OnPostAgregarCliente(Cliente cliente)
        {
            try
            {
                repoCliente.AgregarCliente(cliente);
                this.ObtenerClientes();
            }
            catch
            {
                throw;
            }
        }

        public void OnPostEliminarCliente(string clienteId)
        {
            try
            {
                repoCliente.EliminarCliente(clienteId);
                this.ObtenerClientes();
            }
            catch
            {
                throw;
            }
        }
        private void ObtenerClientes()
        {
            foreach (Cliente cliente in repoCliente.ObtenerClientes())
            {
                this.listaClientes.Add(new Cliente
                {
                    ClienteId = cliente.ClienteId,
                    Nombre = cliente.Nombre,
                    Apellido = cliente.Apellido,
                    Telefono = cliente.Telefono,
                    Rol = cliente.Rol,
                    Correo = cliente.Correo,
                    CiudadResidencia = cliente.CiudadResidencia
                });
            }
        }
    }
}

ProyectoTallerEquipo2/Taller.App/Taller.App.Front/Pages/Propietarios/EditarCliente.cshtml
@page
@model Talle.App.Front.Pages.EditarClienteModel
@{

    <form method="post">
        <div class="mb-3 col-4">
            <label for="entradaIdEditar" class="form-label col-form-label">Id *</label>
            <input type="text" class="form-control" id="entradaIdEditar" disabled="true"
                asp-for="@Model.clienteActual.ClienteId" name="ClienteId" required>
        </div>
        <div class="row">
            <div class="mb-3 col-6">
                <label for="entradaNombresEditar" class="form-label col-form-label">Nombres *</label>
                <input type="text" class="form-control" id="entradaNombresEditar" asp-for="@Model.clienteActual.Nombre"
                    name="Nombre" required>
            </div>
            <div class="mb-3 col-6">
                <label for="entradaApellidosEditar" class="form-label col-form-label">Apellidos
                    *</label>
                <input type="text" class="form-control" id="entradaApellidosEditar" rows="3"
                    asp-for="@Model.clienteActual.Apellido" name="Apellido" required>
            </div>
        </div>
        <div class="row">
            <div class="mb-3 col-6">
                <label for="entradaCelularEditar" class="form-label col-form-label">Número de celular
                    *</label>
                <input type="text" class="form-control" id="entradaCelularEditar" rows="3"
                    asp-for="@Model.clienteActual.Telefono" name="Telefono" required>
            </div>
            <div class="mb-3 col-6">
                <label for="entradaFechaNacimientoEditar" class="form-label col-form-label">Fecha de
                    nacimiento *</label>
                <input type="date" class="form-control" id="entradaFechaNacimientoEditar" rows="3"
                    asp-for="@Model.clienteActual.FechaNacimiento" name="FechaNacimiento" required>
            </div>
        </div>
        <div class="row">
            <div class="mb-3 col-6">
                <label for="entradaCorreoEditar" class="form-label col-form-label">Correo Electrónico
                    *</label>
                <input type="email" class="form-control" id="entradaCorreoEditar" rows="3"
                    asp-for="@Model.clienteActual.Correo" name="Correo" required>
            </div>
            <div class="mb-3 col-6">
                <label for="entradaCiudadResidenciaEditar" class="form-label col-form-label">Ciudad de
                    Residencia *</label>
                <select class="form-select" id="entradaCiudadResidenciaEditar" aria-label="Selecciona una Opción"
                    asp-for="@Model.clienteActual.CiudadResidencia" name="CiudadResidencia" required>
                    <option value="Armenia">Armenia</option>
                    <option value="Bogotá">Bogotá</option>
                    <option value="Cali">Cali</option>
                    <option value="Medellín">Medellín</option>
                    <option value="Meta">Meta</option>
                    <option value="Villavicencio">Villavicencio</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="mb-3 col-6">
                <label for="entradaContraseniaEditar" class="form-label">Contraseña *</label>
                <input type="password" class="form-control" id="entradaContraseniaEditar" rows="3"
                    asp-for="@Model.clienteActual.Contrasenia" name="Contrasenia" required>
            </div>
            <div class="mb-3 col-6">
                <label for="entradaRolEditar" class="form-label">Rol *</label>
                <select class="form-select" id="entradaRolEditar" asp-for="@Model.clienteActual.Rol" name="Rol" required>
                    <option value="Cliente">Propietario</option>
                </select>
            </div>
        </div>
        <a asp-page="/Propietarios/RegistroPropietario" class="btn btn-secondary">Cancelar</a>
        <button type="submit" class="btn btn-primary" asp-page-handler="Editar" asp-route-clienteId="@Model.clienteActual.ClienteId">Editar</button>
    </form>

}

ProyectoTallerEquipo2/Taller.App/Taller.App.Front/Pages/Propietarios/RegistroPropietario.cshtml
@page
@model Taller.App.Front.Pages.RegistroPropietarioModel
@{
}

<div class="class-contain-title">
    <h4>Adicionar un Propietario <i class="bi bi-plus-square-fill class-icon-add" title="Agregar Cliente"
            data-bs-toggle="modal" data-bs-target="#idModalAgregarCliente"></i></h4>
    <form class="form-inline class-search-bar">
        <input type="search" class="form-control mr-sm-2" id="inputBuscar" placeholder="Buscar">
        <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">Buscar</button>
    </form>
</div>
<hr class="border border-primary border-3 opacity-75">
<h3>Datos Propietarios</h3>
<div>
    <form class="">
        <table class="table">
            <thead>
                <tr class="table-primary">
                    <th scope="col">Id</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Teléfono</th>
                    <th scope="col">Rol</th>
                    <th scope="col">Ciudad</th>
                    <th scope="col">Correo</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var c in @Model.listaClientes)
                {
                    <tr>
                        <td>@c.ClienteId</td>
                        <td>@c.Nombre</td>
                        <td>@c.Apellido</td>
                        <td>@c.Telefono</td>
                        <td>@c.Rol</td>
                        <td>@c.CiudadResidencia</td>
                        <td>@c.Correo</td>
                        <td style="display: flex;">
                            <a asp-page="/Propietarios/EditarCliente" asp-route-clienteId="@c.ClienteId">
                                <i class="bi bi-pencil-fill class-icon-edit" title="Editar Cliente"></i>
                            </a>
                            <form method="post">
                                <button class="bi bi-trash3-fill class-icon-del" asp-route-clienteId="@c.ClienteId"
                                asp-page-handler="EliminarCliente" type="submit"></button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </form>
</div>
<div class="modal fade" id="idModalAgregarCliente" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Agregar un Propietario</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post">
                    <div class="row">

                        <div class="mb-3 col-4">
                            <label for="entradaId" class="form-label col-form-label">Id *</label>
                            <input type="text" class="form-control" id="entradaId"
                                asp-for="@Model.clienteActual.ClienteId" name="ClienteId" required>
                        </div>
                        <div class="row">
                            <div class="mb-3 col-6">
                                <label for="entradaNombres" class="form-label col-form-label">Nombres *</label>
                                <input type="text" class="form-control" id="entradaNombres"
                                    asp-for="@Model.clienteActual.Nombre" name="Nombre" required>
                            </div>
                            <div class="mb-3 col-6">
                                <label for="entradaApellidos" class="form-label col-form-label">Apellidos *</label>
                                <input type="text" class="form-control" id="entradaApellidos" rows="3"
                                    asp-for="@Model.clienteActual.Apellido" name="Apellido" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-3 col-6">
                                <label for="entradaCelular" class="form-label col-form-label">Número de celular
                                    *</label>
                                <input type="text" class="form-control" id="entradaCelular" rows="3"
                                    asp-for="@Model.clienteActual.Telefono" name="Telefono" required>
                            </div>
                            <div class="mb-3 col-6">
                                <label for="entradaFechaNacimiento" class="form-label col-form-label">Fecha de
                                    nacimiento *</label>
                                <input type="date" class="form-control" id="entradaFechaNacimiento" rows="3"
                                    asp-for="@Model.clienteActual.FechaNacimiento" name="FechaNacimiento" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-3 col-6">
                                <label for="entradaCorreo" class="form-label col-form-label">Correo Electrónico
                                    *</label>
                                <input type="email" class="form-control" id="entradaCorreo" rows="3"
                                    asp-for="@Model.clienteActual.Correo" name="Correo" required>
                            </div>
                            <div class="mb-3 col-6">
                                <label for="entradaCiudadResidencia" class="form-label col-form-label">Ciudad de
                                    Residencia *</label>
                                <select class="form-select" id="entradaCiudadResidencia"
                                    aria-label="Selecciona una Opción" asp-for="@Model.clienteActual.CiudadResidencia"
                                    name="CiudadResidencia" required>
                                    <option value="Armenia">Armenia</option>
                                    <option value="Bogotá">Bogotá</option>
                                    <option value="Cali">Cali</option>
                                    <option value="Cali">Cali</option>
                                    <option value="Medellín">Medellín</option>
                                    <option value="Meta">Meta</option>
                                    <option value="Villavicencio">Villavicencio</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-3 col-6">
                                <label for="entradaContrasenia" class="form-label">Contraseña *</label>
                                <input type="password" class="form-control" id="entradaContrasenia" rows="3"
                                    asp-for="@Model.clienteActual.Contrasenia" name="Contrasenia" required>
                            </div>
                            <div class="mb-3 col-6">
                                <label for="entradaRol" class="form-label">Rol *</label>
                                <select class="form-select" id="entradaRol" asp-for="@Model.clienteActual.Rol"
                                    name="Rol" required>
                                    <option value="Cliente">Propietario</option>
                                </select>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                            <button type="submit" class="btn btn-primary"
                                asp-page-handler="AgregarCliente">Agregar</button>
                        </div>
                </form>
            </div>
        </div>
    </div>
</div>

@* <div class="modal fade" id="idModalEditarCliente" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Editar Propietario</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
    <form method="post">
    <div class="row">
    <div class="mb-3 col-4">
    <label for="entradaIdEditar" class="form-label col-form-label">Id *</label>
    <input type="text" class="form-control disabled" id="entradaIdEditar"
    asp-for="@Model.clienteActual.ClienteId" name="ClienteId" required>
    </div>
    <div class="row">
    <div class="mb-3 col-6">
    <label for="entradaNombresEditar" class="form-label col-form-label">Nombres *</label>
    <input type="text" class="form-control" id="entradaNombresEditar"
    asp-for="@Model.clienteActual.Nombre" name="Nombre" required>
    </div>
    <div class="mb-3 col-6">
    <label for="entradaApellidosEditar" class="form-label col-form-label">Apellidos *</label>
    <input type="text" class="form-control" id="entradaApellidosEditar" rows="3"
    asp-for="@Model.clienteActual.Apellido" name="Apellido" required>
    </div>
    </div>
    <div class="row">
    <div class="mb-3 col-6">
    <label for="entradaCelularEditar" class="form-label col-form-label">Número de celular
    *</label>
    <input type="text" class="form-control" id="entradaCelularEditar" rows="3"
    asp-for="@Model.clienteActual.Telefono" name="Telefono" required>
    </div>
    <div class="mb-3 col-6">
    <label for="entradaFechaNacimientoEditar" class="form-label col-form-label">Fecha de
    nacimiento *</label>
    <input type="date" class="form-control" id="entradaFechaNacimientoEditar" rows="3"
    asp-for="@Model.clienteActual.FechaNacimiento" name="FechaNacimiento" required>
    </div>
    </div>
    <div class="row">
    <div class="mb-3 col-6">
    <label for="entradaCorreoEditar" class="form-label col-form-label">Correo Electrónico
    *</label>
    <input type="email" class="form-control" id="entradaCorreoEditar" rows="3"
    asp-for="@Model.clienteActual.Correo" name="Correo" required>
    </div>
    <div class="mb-3 col-6">
    <label for="entradaCiudadResidenciaEditar" class="form-label col-form-label">Ciudad de
    Residencia *</label>
    <select class="form-select" id="entradaCiudadResidenciaEditar"
    aria-label="Selecciona una Opción" asp-for="@Model.clienteActual.CiudadResidencia"
    name="CiudadResidencia" required>
    <option value="Armenia">Armenia</option>
    <option value="Bogotá">Bogotá</option>
    <option value="Cali">Cali</option>
    <option value="Cali">Cali</option>
    <option value="Medellín">Medellín</option>
    <option value="Meta">Meta</option>
    <option value="Villavicencio">Villavicencio</option>
    </select>
    </div>
    </div>
    <div class="row">
    <div class="mb-3 col-6">
    <label for="entradaContraseniaEditar" class="form-label">Contraseña *</label>
    <input type="password" class="form-control" id="entradaContraseniaEditar" rows="3"
    asp-for="@Model.clienteActual.Contrasenia" name="Contrasenia" required>
    </div>
    <div class="mb-3 col-6">
    <label for="entradaRolEditar" class="form-label">Rol *</label>
    <select class="form-select" id="entradaRolEditar" asp-for="@Model.clienteActual.Rol"
    name="Rol" required>
    <option value="Cliente">Propietario</option>
    </select>
    </div>

    </div>
    <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
    <button type="submit" class="btn btn-primary"
    asp-page-handler="EditarCliente">Editar</button>
    </div>
    </form>
    </div>
    </div>
    </div>
    </div> *@